---
kubernetes:
  children:
    master:
      hosts:
        m1:
          ansible_host: 10.0.110.18
      vars:
        ansible_user: ubuntu
    worker:
      hosts:
        w1:
          ansible_host: 10.0.110.19
      vars:
        ansible_user: ubuntu

