---
kubernetes:
  children:
    master:
      hosts:
        m1:
          ansible_host: 10.0.105.34
      vars:
        ansible_user: ubuntu
    worker:
      hosts:
        w1:
          ansible_host: 10.0.105.10

