apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:R3Lq24b5,iv:+hENsqIpOz/K8Tq0cOeRczvmdCsaqu0njNvt05eilVs=,tag:Nu3dzNRxOj/MKJOAmJZChg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:JKrZwBfci5eo1riBRsNBCpdXyQYbDDSQiNaj,iv:DHMLXLQDt7BJn/iDAKGxtnJhvEis6FAzU+p8dYjrdk0=,tag:8YEvC9ICFpTEA21yejh0Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-02T22:08:15Z"
    mac: ENC[AES256_GCM,data:6KCRToSPvNUGOZgXiCV3Ycuo/zh8ULbZ4eyLvv8bmWtsTk8bfMZTj+XNFusiF4oGGXZGCIknjsTRX2fIahOf5HX8+Y5AGYnTtkhXifNhvDX77yct9wUuLWwZHxitlbCdD61iDTmORuud3AWEZlR9VMD306eErDM5gDSM3d+9xqI=,iv:20YNSYGgaywL0APEyjjAUawSR5taulEaxtThyOKvhjY=,tag:engmBGnDcC9QyES8oEBZ6g==,type:str]
    pgp:
        - created_at: "2023-03-02T22:08:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzGbrIJF3UKrAQ//TzeFNr2U82OO/KTcF6lZXrO2dEO/Dzh9qro15PZ1qCMY
            Lhs+7CDsDd7liB0cgSVpWE9aErlsm7ZR19HqETvHuzSmQKV2Hen1QkUmXtYo5VUy
            6tZ3tbtg9JnlZyB9o+wQHUBvzUP1fq1q/s3qEVvVXgEglevQvOZj4H3PltqjNj6C
            rXW6zvLyH6Ev0+MpuN20c2KLz/A047I6yt7jquB3irzwPPcYM7xOXzkcOGgcAXGa
            upV2e7ZyidHh+QhtzO73WUFic3NRO+gXUejQOw4MnFUnj8bxVt2wnYJp+u5PVy+7
            LfBByLfjkqrpYNoIz9/1TTq4K+n7jc3J5683HyezCAsddLSJhPy42PMG7svlDUL+
            atKf5sqbq41VsibORu1/Cv3CJfaU7JipBwnhvriUK3Q1gDSCiu0gbnQNA2ar3Q1B
            PVZHo47kAozPuEChT1xWlVX8e7h26AuRRqwwcrVZCP7fc3MyGaNzirhqNSXzbJ9U
            UHRTJbUp10qXpKwIwLR2tr4fYNqms8UZ+1UwYM9IlU7KVxWDvbAJAVwv+yMBU+4S
            Zk4+ySwiXGtjFzJLbZPhh4grmqLFE1HVYyn96uzNMKD7psxwwdGTgf8IJn6+9cGP
            BFJpVvJLbshz+CZeYL7GoZOlocnr3ZNV5Yu396lJKlLNYNa/BjoES9EsJ9X2gn3S
            XgHwukFOKqlgeCTA2JO3Pc0l0UxwHmZdxRXfgTTuCZd3tIxuTdxrMxEQx7ZQGmyb
            DBLxMDPd7yxiZq6SaEUVCUEo+SUftkPnVA69U8VlWIJutYW2/6ymbQuQv2MDeK4=
            =U1qu
            -----END PGP MESSAGE-----
          fp: 6CD908E8381A8B4FA3F20A891CF4D098419C9124
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
