apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
#  - pref-dual-stack
  - netshoot
  - k8s-gateway
  - external-dns/ks.yaml
#  - metallb/ks.yaml
#  - metallb/ks-config.yaml