apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
spec:
  cidrs:
    - cidr: "10.46.1.0/24"
    - cidr: "2001:67c:1104:e04e::/64"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ingress-public-pool"
spec:
  cidrs:
    - cidr: "185.218.193.58/32"
    - cidr: "2001:67c:1104:e03e::443/128"
  serviceSelector:
    matchLabels:
      "cilium.io/ingress": "true"