apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 5
      strategy: rollback
  install:
    createNamespace: true
  chart:
    spec:
      chart: cilium
      version: 1.13.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  values:
    enableIPv6Masquerade: false
    autoDirectNodeRoutes: true
    localRedirectPolicy: true
    rollOutCiliumPods: true
    kubeProxyReplacement: "strict"
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    ipv4NativeRoutingCIDR: "10.45.0.0/16"
    ipv6NativeRoutingCIDR: "2001:67c:1104:e03d::/64"
    k8sServiceHost: "10.0.110.18"
    k8sServicePort: 6443
    loadBalancer:
      algorithm: "maglev"
      mode: "dsr"
    l2NeighDiscovery:
      enabled: false
    tunnel: "disabled"
    endpointRoutes:
      enabled: true
    encryption:
      enabled: false
    ipam:
      mode: "kubernetes"

    ingressController:
      enabled: true
      loadbalancerMode: shared
    ipv6:
      enabled: true
    operator:
      rollOutPods: true
    containerRuntime:
      integration: containerd
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: false
          namespace: kube-system
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          enabled: false
      ui:
        enabled: false

    bgpControlPlane:
      enabled: true

    securityContext:
      privileged: true

    prometheus:
      enabled: false
