---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  install:
    crds: CreateReplace

  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.9
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m
  values:
    controller:
      logLevel: debug
    speaker:
      tolerateMaster: true
      logLevel: info
      frr:
        enabled: true
        image:
          repository: docker.io/frrouting/frr
          tag: v8.4.1
    crds:
      enabled: true
    # https://github.com/cilium/cilium/issues/20436
    # https://github.com/metallb/metallb/issues/1512
    # This is really yank, when I have this many prefixes in use..
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: DaemonSet
              name: metallb-speaker
            patch:
              - op: add
                path: /spec/template/spec/initContainers/3
                value:
                  name: routes
                  command:
                    - /bin/sh
                    - -c
                    - |-
                      ip r add local 10.46.1.0/24 dev lo table local proto 66 scope host || true
                      ip r add local 185.218.193.58/32 dev lo table local proto 66 scope host || true
                      ip -6 r add local 2001:67c:1104:e03e::/112 dev lo table local proto 66 scope host || true
                  image: alpine
                  imagePullPolicy: IfNotPresent
                  securityContext:
                    capabilities:
                      add:
                        - NET_ADMIN
